### ISSUE TITLE
关于打包请教

### ISSUE THREAD

**Issue by 512433465** [qiaojiang/jobflow#2]
<modelVersion>4.0.0</modelVersion>
    <groupId>settle</groupId>
    <artifactId>jobflow</artifactId>
    <packaging>jar</packaging>
    <version>0.1.0</version>

改这里  同一个工程
分别打包成war master worker 么？

**Comment by qiaojiang** [comment]
是的，web程序打包成war，守护进程分别打包成master和worker发自我的华为手机-------- 原始邮件 --------主题：[qiaojiang/jobflow] 关于打包请教 (#2)发件人：hello 收件人：qiaojiang/jobflow 抄送：Subscribed <modelVersion>4.0.0</modelVersion>

<groupId>settle</groupId>

<artifactId>jobflow</artifactId>

<packaging>jar</packaging>

<version>0.1.0</version>



改这里  同一个工程

分别打包成war master worker 么？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/qiaojiang/jobflow/issues/2?email_source=notifications\u0026email_token=ACSJLYO7XFPSYG7ULHGJNITQPP32LA5CNFSM4JCS4RTKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HS7FQDA",

"url": "https://github.com/qiaojiang/jobflow/issues/2?email_source=notifications\u0026email_token=ACSJLYO7XFPSYG7ULHGJNITQPP32LA5CNFSM4JCS4RTKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HS7FQDA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by 512433465** [comment]
非常感谢 老铁回复。谢谢大佬，祝周末愉快！
